name: Test and Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up Python
        run: $HOME/.local/bin/uv python install 3.12

      - name: Install dependencies
        run: $HOME/.local/bin/uv sync

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run tests
        run: $HOME/.local/bin/uv run pytest tests/ -v --ignore=tests/test_integration.py

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ffmpeg-worker:${{ steps.version.outputs.VERSION }} .
          docker tag ffmpeg-worker:${{ steps.version.outputs.VERSION }} ffmpeg-worker:latest

      - name: List images
        run: docker images | grep ffmpeg-worker
